import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/app/components/Sidebar";
import TopBar from "@/app/components/TopBar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-gray-1500 ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="font-neulis-sans pl-64 pt-19.25">
          <div className="p-6">
            <Sidebar />
            {children}
            <TopBar />
          </div>
        </div>
      </body>
    </html>
  );
}
