import "./globals.css";
import { GlobalContextProvider } from "./context/globalContext";


export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalContextProvider>
      <body className={`font-avenir antialiased bg-[#F6F5F9]`}>
        {children}
      </body>
      </GlobalContextProvider>
    </html>
  );
}
