import type { Metadata } from "next";
import Availability from "./components/Availability";
import Header from "./components/Header";
import Partner from "./components/Partner";
import MyModal from "./components/Modal";
import ServiceSlider from "./components/ServiceSlider";
import Accordion from "./components/Accordion";
import Footer from "./components/Footer";
import { BannerVideo } from "./components/BannerVideo";
import ComparisonSlider from "./components/ComparisonSlider";
import { BookCall } from "./components/common/BookCall";
import Link from "next/link";
import SpotsLeft from "./components/spotsLeft";


export const metadata: Metadata = {
  title: "Daasign || Home",
  description: "Generated by create next app",
};

export default function Home() {


  return (
    <div>
      <Header></Header>
      <section className="bg-black-1200 rounded-b-2xl lg:pt-[210px] lg:pb-[490px] pt-[80px] pb-[160px]">
        <div className="max-w-[1280px] mx-auto px-5 relative">
          <div className="text-center">
            <div className="bg-black-1000 rounded-full flex items-center w-fit mx-auto gap-2 py-1.5 px-3">
              <div className="w-[14px] h-[14px] bg-green-1000/[24%] rounded-full p-[3px] block">
                <div className="w-full h-full drop-shadow-3xl rounded-full bg-green-1000"></div>
              </div>
              <h6 className="xl:text-lg md:text-base text-sm font-semibold leading-7 text-gray-1000">For B2B SaaS companies only</h6>
            </div>
            <h1 className="xl:text-[76px] md:text-5xl text-[34px] leading-[40.56px] xl:max-w-full max-w-[500px] md:max-w-[650px] mx-auto md:mt-4 mt-3 md:mb-6 mb-4 font-semibold text-white xl:leading-[91px]">
              We transform your idea into clickable MVP, in just <span className="text-green-1000">5 days</span>
            </h1>
            <p className="xl:text-2xl md:text-lg text-base  md:max-w-[600px] max-w-[400px] mb-10 font-medium text-gray-1000 xl:max-w-[712px] mx-auto font-grotesque-arabic-pro">
              After designing your MVP, you saved development costs, can validate your idea, raise investments, and
              attract your first users.
            </p>
            <ul className="flex sm:flex-row flex-col items-center justify-center gap-6">
              <li className="w-full sm:w-fit">
             <BookCall/>
              </li>
              <li className="w-full sm:w-fit">
                <Link href="/#pricing-sec" 
                  className="md:text-lg sm:w-fit w-full text-sm font-semibold leading-7 inline-block text-gray-1100 border border-gray-1100 bg-transparent rounded-lg py-2.5 px-5">
                  Order your MVP
                </Link>
              </li>
            </ul>
          </div>
          <img src="/images/Hero_Label1.svg" className="absolute lg:block hidden xl:w-fit w-[200px] xl:top-[-75px] top-[-45px] left-2" alt="no img" />
          <img src="/images/Hero_Label2.svg" className="absolute lg:block hidden xl:w-fit w-[200px] bottom-[35px] right-2 xl:right-[-30px]" alt="no img" />
          <img src="/images/Hero_Label3.svg" className="absolute lg:block hidden xl:w-fit w-[200px] bottom-[-90px] xl:-left-10 left-2" alt="no img" />
        </div>
      </section>
      <BannerVideo/>
      <Partner></Partner>
      <section className=" md:pt-10 pt-3 md:pb-20 pb-8">
        <div className="max-w-[1300px] mx-auto px-5">
        <div className="w-full mb-20">
          <div className="mx-auto max-w-[460px] mb-10">
              <p className="lg:text-lg md:text-base text-sm font-semibold mb-2 text-center text-black-1200">You might be facing one of the following challenges</p>
              <h2 className="text-[42px] text-black-1200 font-semibold text-center font-gilroy">As a SaaS founder...</h2>
          </div>
          <div className="grid md:grid-cols-3 grid-cols-1 md:gap-5 gap-3">
            <div className="bg-gray-1100 border border-gray-1200 rounded-[16px] text-center lg:p-8 p-5">
              <div className="flex items-center justify-center mx-auto">
                <img src="images/dev-icon.svg" alt="no img"></img>
              </div>
              <h4 className="md:text-[28px] text-xl font-semibold leading-8 text-black-1200 md:mt-6 mt-3 mb-1.5 md:mb-2">High dev. costs</h4>
              <p className="md:text-lg text-sm md:leading-7 leading-normal text-black-1200 font-grotesque-arabic-pro">
              Jumping into development seems smart —but isn’t. Start from a user centric design approach first & build once.
              </p>
            </div>
            <div className="bg-gray-1100 border border-gray-1200 rounded-[16px] text-center lg:p-8 p-5">
            <div className="flex items-center justify-center mx-auto">
                <img src="images/progress-icon.svg" alt="no img"></img>
              </div>
              <h4 className="md:text-[28px] text-xl font-semibold leading-8 text-black-1200 md:mt-6 mt-3 mb-1.5 md:mb-2">No validation, no progress</h4>
              <p className="md:text-lg text-sm md:leading-7 leading-normal text-black-1200 font-grotesque-arabic-pro">
              Building without validation is a gamble—test, measure, and learn to avoid wasting time and money.
              </p>
            </div>
            <div className="bg-gray-1100 border border-gray-1200 rounded-[16px] text-center lg:p-8 p-5">
              <div className="flex items-center justify-center mx-auto">
                <img src="images/Time-icon.svg" alt="no img"></img>
              </div>
              <h4 className="md:text-[28px] text-xl font-semibold leading-8 text-black-1200 md:mt-6 mt-3 mb-1.5 md:mb-2">Time consuming</h4>
              <p className="md:text-lg text-sm md:leading-7 leading-normal text-black-1200 font-grotesque-arabic-pro">
              Doing it yourself slows down your time-to-market and makes it hard to outpace competitors
              </p>
            </div>
          </div>
          </div>

          <div className="w-full">
          <div className="mx-auto max-w-[460px] mb-10">
              <p className="lg:text-lg md:text-base text-sm font-semibold mb-2 text-center text-black-1200">Our solution</p>
              <h2 className="text-[42px] text-black-1200 font-semibold text-center font-gilroy">You will get...</h2>
          </div>
          <div className="grid md:grid-cols-3 grid-cols-1 md:gap-5 gap-3">
            <div className="bg-gray-1100 border border-gray-1200 rounded-[16px] text-center lg:p-8 p-5">
              <div className="flex items-center justify-center mx-auto">
                <img src="images/hrs-icon.svg" alt="no img"></img>
              </div>
              <h4 className="md:text-[28px] text-xl font-semibold leading-8 text-black-1200 md:mt-6 mt-3 mb-1.5 md:mb-2">4 hrs time commitment</h4>
              <p className="md:text-lg text-sm md:leading-7 leading-normal text-black-1200 font-grotesque-arabic-pro">
              No useless meetings so you can focus on what matters as a founder
              </p>
            </div>
            <div className="bg-gray-1100 border border-gray-1200 rounded-[16px] text-center lg:p-8 p-5">
            <div className="flex items-center justify-center mx-auto">
                <img src="images/customer-icon.svg" alt="no img"></img>
              </div>
              <h4 className="md:text-[28px] text-xl font-semibold leading-8 text-black-1200 md:mt-6 mt-3 mb-1.5 md:mb-2">100% custom design</h4>
              <p className="md:text-lg text-sm md:leading-7 leading-normal text-black-1200 font-grotesque-arabic-pro">
              We design everything custom and did it for  50+ SaaS companies
              </p>
            </div>
            <div className="bg-gray-1100 border border-gray-1200 rounded-[16px] text-center lg:p-8 p-5">
              <div className="flex items-center justify-center mx-auto">
                <img src="images/calendar2-icon.svg" alt="no img"></img>
              </div>
              <h4 className="md:text-[28px] text-xl font-semibold leading-8 text-black-1200 md:mt-6 mt-3 mb-1.5 md:mb-2">Done in 5 business days</h4>
              <p className="md:text-lg text-sm md:leading-7 leading-normal text-black-1200 font-grotesque-arabic-pro">
              From kick-off to fully designed MVP in 5 days, ready for development
              </p>
            </div>
          </div>
          </div>
          <div className="text-center sm:mt-10 mt-5">
            <Link href="/#pricing-sec"
              className="md:text-lg text-sm  sm:w-fit w-full font-semibold md:leading-7 leading-normal text-gray-1100 py-2.5 px-5 inline-block rounded-md bg-black-1200">
              Order your MVP
            </Link>
          </div>
        </div>
      </section>
      <Availability></Availability>
      <section id="work-sec" className="bg-black-1200 rounded-b-2xl relative md:pt-5 pt-3 md:pb-20 pb-8">
        <div className="max-w-[1300px] px-5 mx-auto">
          <div className="text-center">
            <span className="block font-semibold md:text-lg text-sm md:leading-7 leading-normal text-gray-1000 md:mb-2 mb-1">How does it work?</span>
            <h2 className="md:text-[42px] text-[26px] font-semibold md:leading-[50px] text-gray-1000">Zero to One MVP in 5 days -{">"} Idea to MVP in 5 days</h2>
          </div>
          <div className="grid lg:grid-cols-4 md:grid-cols-2 grid-cols-1 md:gap-5 gap-3 md:my-10 my-5">
            <div className="bg-black-1100 border border-white/[10%] rounded-2xl md:px-8 md:py-8 p-5 lg:min-h-[344px]">
              <div className="md:w-[60px] md:h-[60px] w-12 h-12 p-2.5 bg-orange-1000/[12%] rounded-full flex items-center justify-center">
                <img src="images/search-icon.svg" alt=""></img>
              </div>
              <h4 className="md:text-[32px] text-[22px] font-semibold md:leading-8 text-gray-1000 md:mt-8 mt-4 md:mb-4 mb-1.5">1. Connect</h4>
              <p className="md:text-lg text-sm font-normal md:leading-7 leading-normal  font-grotesque-arabic-pro2 text-gray-1000">
                Focussing on understanding your vision and which problem you want to solve.
              </p>
            </div>
            <div className="bg-black-1100 border border-white/[10%] rounded-2xl md:px-8 md:py-8 p-5 lg:min-h-[344px]">
              <div className="md:w-[60px] md:h-[60px] w-12 h-12 p-2 bg-green-1000/[12%] rounded-full flex items-center justify-center">
                <img src="images/bubble-service.svg" alt=""></img>
              </div>
              <h4 className="md:text-[32px] text-[22px] font-semibold md:leading-8 text-gray-1000 md:mt-8 mt-4 md:mb-4 mb-1.5">2. Concept</h4>
              <p className="md:text-lg text-sm font-normal md:leading-7 leading-normal  font-grotesque-arabic-pro2 text-gray-1000">
                Translating requirements into features and mapping out the customer journey with a well defined
                flowchart.
              </p>
            </div>
            <div className="bg-black-1100 border border-white/[10%] rounded-2xl md:px-8 md:py-8 p-5 lg:min-h-[344px]">
              <div className="md:w-[60px] md:h-[60px] w-12 h-12 p-2 bg-blue-1000/[12%] rounded-full flex items-center justify-center">
                <img src="images/create-icon.svg" alt=""></img>
              </div>
              <h4 className="md:text-[32px] text-[22px] font-semibold md:leading-8 text-gray-1000 md:mt-8 mt-4 md:mb-4 mb-1.5">3. Create</h4>
              <p className="md:text-lg text-sm font-normal md:leading-7 leading-normal  font-grotesque-arabic-pro2 text-gray-1000">
                Design high-fidelity prototype and making ready for implementation and coding.
              </p>
            </div>
            <div className="bg-black-1100 border border-white/[10%] rounded-2xl md:px-8 md:py-8 p-5 lg:min-h-[344px]">
              <div className="md:w-[60px] md:h-[60px] w-12 h-12 p-2 bg-gray-1300/[12%] rounded-full flex items-center justify-center">
                <img src="images/msg-icon.svg" alt=""></img>
              </div>
              <h4 className="md:text-[32px] text-[22px] font-semibold md:leading-8 text-gray-1000 md:mt-8 mt-4 md:mb-4 mb-1.5">4. Validate</h4>
              <p className="md:text-lg text-sm font-normal md:leading-7 leading-normal  font-grotesque-arabic-pro2 text-gray-1000">
                After designing your MVP we are ready to validate our idea and gather feedback.
              </p>
            </div>
          </div>
          <div className="text-center">
          <BookCall/>
          </div>
        </div>
      </section>
      <section className=" bg-white lg:mt-20 -mt-5 lg:py-20 py-12">
        <div className="max-w-[1320px] mx-auto px-5">
          <div className="text-center md:mb-10 mb-5">
            <span className="block font-semibold md:text-lg text-sm md:leading-7 leading-normal text-black-1300 mb-2">
              Worked with over 50+ SaaS companies over the years
            </span>
            <h2 className="md:text-[42px] text-[26px] font-semibold md:leading-[50px] text-black-1300">
              What do other SaaS founders say?
            </h2>
          </div>
          <div className="flex lg:flex-row flex-col gap-6">
            <div className="lg:w-1/4 w-full flex flex-col">
              <div className="relative maw-w-[400px]">
                <img src="images/testimonial-img.png" className="w-full rounded-xl object-cover h-[320px] lg:h-full" alt="no-img"></img>
                <MyModal></MyModal>
              </div>
              <div className="bg-green-1000  rounded-xl 2xl:p-10 p-5 flex flex-col h-full justify-center mt-6">
                <h4 className="2xl:text-[40px] text-3xl font-semibold 2xl:leading-[48px] mb-6 text-black-1200">
                  Lorem ipsum dolor sit amet.
                </h4>
                <span className="text-base font-semibold text-black-1200 block">
                  Julien Kreuk
                  <br></br>Data Scientist @Daasign
                </span>
              </div>
            </div>
            <div className="lg:w-3/4 w-full flex flex-col">
              <div className="flex lg:flex-row flex-col gap-6 mb-6">
                <div className="bg-black-1200 lg:max-w-[320px] rounded-xl 2xl:py-11 pr-6 p-5 2xl:px-10">
                  <h4 className="2xl:text-2xl lg:text-xl font-medium font-grotesque-arabic-pro text-gray-1200 mb-6">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit sed.{" "}
                  </h4>
                  <div className="flex items-center gap-2">
                    <img src="images/avatar.png" alt="" className="rounded-full w-[54px] h-[54px]"></img>
                    <div>
                      <h6 className="md:text-lg text-sm font-semibold md:leading-7 leading-normal text-gray-1100 mb-0.5">Julien Kreuk</h6>
                      <span className="block text-base font-semibold leading-5 text-gray-1200">
                        Data Scientist @Daasign
                      </span>
                    </div>
                  </div>
                </div>
                <div className="bg-gray-1200 rounded-xl 2xl:p-10 2xl:pb-12 p-5">
                  <h2 className="2xl:text-[28px] md:text-xl text-xl font-semibold lg:leading-8 text-black-1200 mb-6">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit sed. Lorem ipsum dolor. scscvdsdvsdv
                  </h2>
                  <div>
                    <h6 className="md:text-lg text-sm font-semibold md:leading-7 leading-normal text-black-1200 mb-0.5">Julien Kreuk</h6>
                    <span className="block text-base font-semibold leading-5 text-black-1200">
                      Data Scientist @Daasign
                    </span>
                  </div>
                </div>
              </div>
              <div className="flex lg:flex-row flex-col gap-6">
                <div className="relative">
                  <img src="images/testimonial-img2.png" className="w-full rounded-xl object-cover h-[320px] lg:h-full" alt=""></img>
                  <MyModal></MyModal>
                </div>
                <div className="lg:max-w-[320px] w-full flex flex-col">
                  <div className="bg-green-1000 mb-6 rounded-xl 2xl:p-10 2lx:py-7 p-5">
                    <h4 className="2xl:text-2xl lg:text-xl text-2xl font-grotesque-arabic-pro font-medium leading-[30px] mb-6 text-black-1200">
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit sed.{" "}
                    </h4>
                    <span className="text-base font-semibold text-black-1200 block">
                      Julien Kreuk
                      <br></br>Data Scientist @Daasign
                    </span>
                  </div>
                  <div className="bg-black-1200 w-full lg:max-w-[320px] flex flex-col rounded-xl 2xl:p-8 p-5 h-full">
                    <h4 className="2xl:text-2xl lg:text-xl text-base font-medium font-grotesque-arabic-pro text-gray-1200 mb-6">
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit sed. Lorem ipsum dolor sit amet,
                      consectetur adipiscing elit sed.{" "}
                    </h4>
                    <div className="flex items-center gap-2 mt-auto">
                      <img src="images/avatar.png" alt="" className="rounded-full w-[54px] h-[54px]"></img>
                      <div>
                        <h6 className="md:text-lg text-sm font-semibold md:leading-7 leading-normal text-gray-1100 mb-0.5">Julien Kreuk</h6>
                        <span className="block text-base font-semibold leading-5 text-gray-1200">
                          Data Scientist @Daasign
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="pricing-sec" className=" bg-gray-1000 lg:py-20 py-8">
        <div className="max-w-[1320px] px-5 mx-auto">
          <div className="flex lg:flex-row flex-col items-center lg:gap-6 gap-10">
            <div className="lg:w-1/2 md:w-4/5 w-full">
            <div className="border border-gray-1200 mb-4 rounded-2xl bg-gray-1100 p-5 flex items-center gap-6">
                <div className="bg-gray-1400 md:w-[60px] md:h-[60px] w-12 h-12 p-2 rounded-full flex items-center justify-center">
                  <img src="images/check.svg" alt="no-img"></img>
                </div>
                <div className="flex-1">
                  <h6 className="md:text-2xl text-xl font-grotesque-arabic-pro font-medium text-black-1200">
                  Good design = well received by investores
                  </h6>
                </div>
              </div>
              <div className="border border-gray-1200 mb-4 rounded-2xl bg-gray-1100 p-5 flex items-center gap-6">
                <div className="bg-gray-1400 md:w-[60px] md:h-[60px] w-12 h-12 p-2 rounded-full flex items-center justify-center">
                  <img src="images/check.svg" alt="no-img"></img>
                </div>
                <div className="flex-1">
                  <h6 className="md:text-2xl text-xl font-grotesque-arabic-pro font-medium text-black-1200">
                  Done in less than a week
                  </h6>
                </div>
              </div>
              <div className="border border-gray-1200 mb-4 rounded-2xl bg-gray-1100 p-5 flex items-center gap-6">
                <div className="bg-gray-1400 md:w-[60px] md:h-[60px] w-12 h-12 p-2 rounded-full flex items-center justify-center">
                  <img src="images/check.svg" alt=""></img>
                </div>
                <div className="flex-1">
                  <h6 className="md:text-2xl text-xl font-grotesque-arabic-pro font-medium text-black-1200">
                    50% faster time-to-market by ditching development costs
                  </h6>
                </div>
              </div>
              <div className="border border-gray-1200 mb-4 rounded-2xl bg-gray-1100 p-5 flex items-center gap-6">
                <div className="bg-gray-1400 md:w-[60px] md:h-[60px] w-12 h-12 p-2 rounded-full flex items-center justify-center">
                  <img src="images/check.svg" alt=""></img>
                </div>
                <div className="flex-1">
                  <h6 className="md:text-2xl text-xl font-grotesque-arabic-pro font-medium text-black-1200">Designed 50+ MVPs</h6>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <img src="images/avatar.png" alt="" className="rounded-full w-[54px] h-[54px]"></img>
                <div>
                  <h6 className="md:text-lg text-sm font-extrabold md:leading-7 leading-normal text-black-1200 mb-0.5">Julien Kreuk</h6>
                  <span className="block text-base font-semibold leading-5 text-black-1200">
                  Product Designer @Daasign
                  </span>
                </div>
              </div>
            </div>
            <div className="lg:w-1/2 md:w-4/5 w-full">
              <div className="bg-black-1200 lg:max-w-[538px] lg:ml-auto rounded-2xl lg:p-10 p-6">
                <div className="flex items-center gap-4 pb-4 mb-4 border-b border-black-1100">
                  <div className="bg-green-1000/[12%] rounded-full md:w-[60px] md:h-[60px] w-12 h-12 p-2 flex items-center justify-center">
                    <img src="images/building-castle.svg" alt=""></img>
                  </div>
                  <h4 className="md:text-[42px] text-[26px] font-semibold md:leading-[50px] text-gray-1000">MVP design</h4>
                </div>
                <h3 className="text-white md:text-[40px] text-4xl font-semibold leading-[48px] mb-5">
                  <span className="text-2xl">From</span> € 5.000
                </h3>
                <div className="pb-5 border-b border-black-1100">
                  <ul className="list-disc ml-5">
                    <li className="md:text-lg text-sm font-grotesque-arabic-pro2 font-normal md:leading-7 leading-normal mb-2 text-white">
                      <p>Discovery session</p>
                    </li>
                    <li className="md:text-lg text-sm font-grotesque-arabic-pro2 font-normal md:leading-7 leading-normal mb-2 text-white">
                      <p>Mock-ups with 2 features</p>
                    </li>
                    <li className="md:text-lg text-sm font-grotesque-arabic-pro2 font-normal md:leading-7 leading-normal text-white">
                      <p>3 feedback rounds</p>
                    </li>
                  </ul>
                </div>
                <h6 className="md:text-lg text-sm pt-4 font-semibold md:leading-7 leading-normal text-white mb-2.5">Deliverables</h6>
                <ul className="mb-5">
                  <li className="flex items-center gap-2 mb-2 md:text-lg text-sm font-normal text-white font-grotesque-arabic-pro2">
                    <span>
                      <img src="images/tick-circle.svg" alt=""></img>
                    </span>
                    Processing diagram
                  </li>
                  <li className="flex items-center gap-2 mb-2 md:text-lg text-sm font-normal text-white font-grotesque-arabic-pro2">
                    <span>
                      <img src="images/tick-circle.svg" alt=""></img>
                    </span>
                    2 email templates
                  </li>
                  <li className="flex items-center gap-2 mb-2 md:text-lg text-sm font-normal text-white font-grotesque-arabic-pro2">
                    <span>
                      <img src="images/tick-circle.svg" alt=""></img>
                    </span>
                    Clickable prototype
                  </li>
                  <li className="flex items-center gap-2 md:text-lg text-sm font-normal text-white font-grotesque-arabic-pro2">
                    <span>
                      <img src="images/tick-circle.svg" alt=""></img>
                    </span>
                    Design files ready for development
                  </li>
                </ul>
                <Link href="https://buy.stripe.com/5kA6rK89a2xF1Uc4gg"
                  className="md:text-lg block text-sm font-semibold md:leading-7 leading-normal w-full text-black-1200 bg-green-1000 rounded-lg py-2.5 text-center px-5">
                  Order your MVP
                </Link>
               <SpotsLeft/>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="case-study-sec" className="py-8 lg:px-0 px-5">
        <div className="text-center md:mb-10 mb-5">
          <h2 className="md:text-[42px] text-[26px] px-5 font-semibold md:leading-[50px] text-black-1000">
            We can (re-)design your current MVP or create a new one
          </h2>
        </div>
        <div className="lg:pl-[calc(50vw_-_640px)] ml-auto">
          <ServiceSlider></ServiceSlider>
        </div>
      </section>
      <section className="lg:pt-20 pt-8 relative">
        <div className="w-full bg-black-1200 h-[600px] rounded-t-3xl absolute z-0 bottom-0"></div>
        <div className="max-w-[1320px] px-5 mx-auto relative">
          <div className="md:bg-gray-1100 rounded-2xl 2xl:p-20 md:p-10">
            <div className="text-center md:mb-0 mb-5">
              <span className="block font-semibold text-lg md:leading-7 leading-normal text-black-1000 mb-2">Comparison</span>
              <h2 className="md:text-[42px] text-[26px] font-semibold md:leading-[50px] text-black-1000">Why Daasign</h2>
            </div>
            <ComparisonSlider></ComparisonSlider>
            <table className="w-full md:table hidden">
              <thead>
                <tr>
                  <th scope="col" className="opacity-0 py-6 px-8"></th>
                  <th scope="col" className="py-6 px-8">
                    <div className="text-center md:text-2xl text-xl font-grotesque-arabic-pro font-medium text-black-1200">
                      In-house design
                    </div>
                  </th>
                  <th scope="col" className="py-6 px-8">
                    {" "}
                    <div className="text-center md:text-2xl text-xl font-grotesque-arabic-pro font-medium text-black-1200">
                      Agency
                    </div>
                  </th>
                  <th scope="col" className="py-6 px-8">
                    {" "}
                    <div className="text-center md:text-2xl text-xl font-grotesque-arabic-pro font-medium text-black-1200">
                      Daasign
                    </div>
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th className="py-4 px-6 text-lg font-normal md:leading-7 leading-normal text-black-1200 text-start">
                    Project management
                  </th>
                  <td>
                    <div className="w-[30px] h-[30px] bg-gray-1400/[80%] mx-auto rounded-full flex items-center justify-center">
                      <img src="images/check-2.svg" alt=""></img>
                    </div>
                  </td>
                  <td>
                    {" "}
                    <div className="w-[30px] h-[30px] bg-gray-1400/[80%] mx-auto rounded-full flex items-center justify-center">
                      <img src="images/check-2.svg" alt=""></img>
                    </div>
                  </td>
                  <td className="bg-gray-1500 rounded-t-2xl">
                    {" "}
                    <div className="w-[30px] h-[30px] bg-gray-1400/[80%] mx-auto rounded-full flex items-center justify-center">
                      <img src="images/check-2.svg" alt=""></img>
                    </div>
                  </td>
                </tr>
                <tr>
                  <th className="py-4 px-6 text-lg font-normal md:leading-7 leading-normal text-black-1200 text-start">
                    Understand your needs
                  </th>
                  <td>
                    <div className="w-[30px] h-[30px] bg-gray-1400/[80%] mx-auto rounded-full flex items-center justify-center">
                      <img src="images/check-2.svg" alt=""></img>
                    </div>
                  </td>
                  <td>
                    {" "}
                    <div className="w-[30px] h-[30px] bg-gray-1400/[80%] mx-auto rounded-full flex items-center justify-center">
                      <img src="images/check-2.svg" alt=""></img>
                    </div>
                  </td>
                  <td className="bg-gray-1500">
                    {" "}
                    <div className="w-[30px] h-[30px] bg-gray-1400/[80%] mx-auto rounded-full flex items-center justify-center">
                      <img src="images/check-2.svg" alt=""></img>
                    </div>
                  </td>
                </tr>
                <tr>
                  <th className="py-4 px-6 text-lg font-normal md:leading-7 leading-normal text-black-1200 text-start">
                  Technical knowlegde
                  </th>
                  <td>
                    <div className="w-[30px] h-[30px] bg-red-1000 mx-auto rounded-full flex items-center justify-center">
                      <img src="images/close.svg" alt=""></img>
                    </div>
                  </td>
                  <td>
                    {" "}
                    <div className="w-[30px] h-[30px] bg-gray-1400/[80%] mx-auto rounded-full flex items-center justify-center">
                      <img src="images/check-2.svg" alt=""></img>
                    </div>
                  </td>
                  <td className="bg-gray-1500">
                    {" "}
                    <div className="w-[30px] h-[30px] bg-gray-1400/[80%] mx-auto rounded-full flex items-center justify-center">
                      <img src="images/check-2.svg" alt=""></img>
                    </div>
                  </td>
                </tr>
                <tr>
                  <th className="py-4 px-6 text-lg font-normal md:leading-7 leading-normal text-black-1200 text-start">
                    SaaS MVP expertise
                  </th>
                  <td>
                    <div className="w-[30px] h-[30px] bg-red-1000 mx-auto rounded-full flex items-center justify-center">
                      <img src="images/close.svg" alt=""></img>
                    </div>
                  </td>
                  <td>
                    {" "}
                    <div className="w-[30px] h-[30px] bg-gray-1400/[80%] mx-auto rounded-full flex items-center justify-center">
                      <img src="images/check-2.svg" alt=""></img>
                    </div>
                  </td>
                  <td className="bg-gray-1500">
                    {" "}
                    <div className="w-[30px] h-[30px] bg-gray-1400/[80%] mx-auto rounded-full flex items-center justify-center">
                      <img src="images/check-2.svg" alt=""></img>
                    </div>
                  </td>
                </tr>
                <tr>
                  <th className="py-4 px-6 text-lg font-normal md:leading-7 leading-normal text-black-1200 text-start">Low overhead</th>
                  <td>
                    <div className="w-[30px] h-[30px] bg-red-1000 mx-auto rounded-full flex items-center justify-center">
                      <img src="images/close.svg" alt=""></img>
                    </div>
                  </td>
                  <td>
                    {" "}
                    <div className="w-[30px] h-[30px] bg-red-1000 mx-auto rounded-full flex items-center justify-center">
                      <img src="images/close.svg" alt=""></img>
                    </div>
                  </td>
                  <td className="bg-gray-1500">
                    {" "}
                    <div className="w-[30px] h-[30px] bg-gray-1400/[80%] mx-auto rounded-full flex items-center justify-center">
                      <img src="images/check-2.svg" alt=""></img>
                    </div>
                  </td>
                </tr>
                <tr>
                  <th className="py-4 px-6 text-lg font-normal leading-7 text-black-1200 text-start">
                  Hours of meetings
                  </th>
                  <td>
                  <div className="flex items-center justify-center">
                        <span className="text-center text-lg font-semibold text-black-1200">≈ 40+ hours</span>
                    </div>
                  </td>
                  <td>
                    {" "}
                    <div className="flex items-center justify-center">
                        <span className="text-center text-lg font-semibold text-black-1200">≈ 16 hours</span>
                    </div>
                  </td>
                  <td className="bg-gray-1500">
                    {" "}
                    <div className="flex items-center justify-center">
                        <span className="text-center text-lg font-semibold text-black-1200">4 hours</span>
                    </div>
                  </td>
                </tr>
                <tr>
                  <th className="py-4 px-6 text-lg font-normal leading-7 text-black-1200 text-start">
                  Speed
                  </th>
                  <td>
                    <div className="flex items-center justify-center">
                        <span className="text-center text-lg font-semibold text-black-1200">Weeks</span>
                    </div>
                  </td>
                  <td>
                    {" "}
                    <div className="flex items-center justify-center">
                        <span className="text-center text-lg font-semibold text-black-1200">Weeks</span>
                    </div>
                  </td>
                  <td className="bg-gray-1500">
                    {" "}
                    <div className="flex items-center justify-center">
                        <span className="text-center text-lg font-semibold text-black-1200">5 days</span>
                    </div>
                  </td>
                </tr>
            
                <tr>
                  <th className="py-4 px-6 text-lg font-normal leading-7 text-black-1200 text-start">Avg. costs</th>
                  <td>
                    <div className="text-center">
                      <h6 className="text-2xl font-semibold leading-7 text-black-1200">≈ €70.000/yr</h6>
                      <span className="text-center text-base font-medium text-black-1200">salary sr. designer</span>
                    </div>
                  </td>
                  <td>
                    {" "}
                    <div className="text-center">
                      <h6 className="text-2xl font-semibold leading-7 text-black-1200">≈ €20.000</h6>
                    </div>
                  </td>
                  <td className="bg-gray-1500 rounded-b-xl">
                    {" "}
                    <div className="text-center">
                      <h6 className="text-2xl font-semibold leading-7 text-black-1200">€5.000</h6>
                      <span className="text-center text-base font-medium text-black-1200">one-time payment</span>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <div className="text-center px-3 xl:py-20 py-10" >
            <h2 className="md:text-[42px] text-[26px] md:mb-10 mb-5 font-semibold md:leading-[50px] text-gray-1000">
              Bring your ideas to life in just a few days
            </h2>
         <BookCall/>
          </div>
        </div>
      </section>
      <section id="faqs-sec" className="bg-black-1200 py-10 ">
        <div className="max-w-[1320px] mx-auto px-5">
          <h2 className="md:text-[42px] text-[26px] md:mb-10 mb-0 font-semibold text-center md:leading-[50px] text-gray-1000">
            Frequently asked questions
          </h2>
          <Accordion></Accordion>
        </div>
        <Footer></Footer>
      </section>
    </div>
  );
}
