import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { TranslationProvider } from "./contexts/TranslationContext";
import PageWrapper from './components/PageWrapper';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} bg-gray-1400 font-geist dark:bg-black-1100 antialiased`}>
          <TranslationProvider>
      
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <PageWrapper>
              {children}
            </PageWrapper>
        </ThemeProvider>
          </TranslationProvider>
      </body>
    </html>
  );
}